window.IUMP_MOCK_DATA = {
  app: {
    name: 'IDEA Utility Monitoring Platform',
    shortName: 'IUMP',
    environment: 'PROTOTYPE',
    version: 'UI v0.1',
    lastRefresh: '23/07/2026 10:25:42 ICT',
    site: 'IDEA Factory A',
    area: 'All areas',
    timezone: 'Asia/Ho_Chi_Minh',
    user: { name: 'Trần Minh', role: 'Operator', initials: 'TM' }
  },
  sites: [
    { id: 'site-a', name: 'IDEA Factory A', timezone: 'Asia/Ho_Chi_Minh' },
    { id: 'site-b', name: 'IDEA Factory B', timezone: 'Asia/Ho_Chi_Minh' }
  ],
  qualitySummary: [
    { label: 'Good', value: 92, count: 1102 },
    { label: 'Uncertain', value: 3, count: 36 },
    { label: 'Bad', value: 1, count: 12 },
    { label: 'Missing', value: 4, count: 48 }
  ],
  sources: [
    { id: 'src-rest-01', name: 'REST-01', type: 'REST API', state: 'Online', lastSeen: '15 sec ago', accepted: '99.8%' },
    { id: 'src-sim-02', name: 'SIMULATOR-02', type: 'Simulator', state: 'Online', lastSeen: '10 sec ago', accepted: '100%' },
    { id: 'src-csv-08', name: 'CSV-BATCH-08', type: 'CSV Import', state: 'Completed', lastSeen: '08:40', accepted: '98.4%' },
    { id: 'src-edge-01', name: 'EDGE-01', type: 'Conditional / MVP-2', state: 'Not enabled', lastSeen: '—', accepted: '—' },
    { id: 'src-rest-04', name: 'REST-04', type: 'REST API', state: 'Stale', lastSeen: '8 min ago', accepted: '96.7%' }
  ],
  points: {
    'point-power-a': {
      id: 'point-power-a',
      code: 'MAIN-PANEL-A-POWER',
      name: 'Main Panel A — Active Power',
      metric: 'Power',
      unit: 'kW',
      value: 128.7,
      quality: 'Good',
      timestamp: '23/07/2026 10:25:00 ICT',
      interval: '60 seconds',
      source: 'REST-01',
      site: 'IDEA Factory A',
      area: 'Utility Area',
      asset: 'Main Panel A',
      coverage: 95.4,
      validRecords: 1102,
      missingIntervals: 54,
      min: 105.2,
      max: 135.8,
      avg: 118.6,
      alertIds: ['ALT-2026-0031'],
      ruleIds: ['PWR-001'],
      series: [
        108, 110, 112, 111, 115, 117, 116, 119, 121, 118,
        120, 122, 126, 129, 131, 130, 127, null, null, null,
        124, 126, 128, 132, 134, 133, 129, 128.7
      ],
      timestamps: [
        '08:00','08:05','08:10','08:15','08:20','08:25','08:30','08:35','08:40','08:45',
        '08:50','08:55','09:00','09:05','09:10','09:15','09:20','09:25','09:30','09:35',
        '09:40','09:45','09:50','09:55','10:00','10:05','10:10','10:25'
      ]
    },
    'point-compressor-a': {
      id: 'point-compressor-a',
      code: 'COMPRESSOR-A-POWER',
      name: 'Compressor A — Power',
      metric: 'Power',
      unit: 'kW',
      value: 122.4,
      quality: 'Good',
      timestamp: '23/07/2026 10:24:00 ICT',
      interval: '60 seconds',
      source: 'SIMULATOR-02',
      site: 'IDEA Factory A',
      area: 'Compressed Air',
      asset: 'Compressor A',
      coverage: 98.2,
      validRecords: 1168,
      missingIntervals: 22,
      min: 70.2,
      max: 129.4,
      avg: 91.5,
      alertIds: ['ALT-2026-0027'],
      ruleIds: ['PWR-001'],
      series: [72,74,77,80,82,85,84,86,89,91,94,97,102,108,114,119,123,126,129,128,126,124,123,122.4],
      timestamps: ['08:00','08:06','08:12','08:18','08:24','08:30','08:36','08:42','08:48','08:54','09:00','09:06','09:12','09:18','09:24','09:30','09:36','09:42','09:48','09:54','10:00','10:06','10:12','10:24']
    }
  },
  rules: {
    'PWR-001': {
      id: 'PWR-001',
      name: 'Power High Limit',
      version: 3,
      state: 'Active',
      type: 'Threshold',
      operator: '>',
      threshold: 120,
      unit: 'kW',
      duration: '5 minutes',
      cooldown: '30 minutes',
      severity: 'Critical',
      owner: 'Lê Anh',
      reviewer: 'Nguyễn Hoàng',
      purpose: 'Alert when active power remains above the approved operating limit.',
      scope: 'IDEA Factory A / Utility Area / Main Panel A / Active Power'
    },
    'NODATA-004': {
      id: 'NODATA-004',
      name: 'Compressor B — No Data',
      version: 2,
      state: 'Active',
      type: 'No Data',
      duration: '5 minutes',
      severity: 'High',
      owner: 'Lê Anh',
      reviewer: 'Nguyễn Hoàng'
    }
  },
  alerts: [
    {
      id: 'ALT-2026-0031',
      title: 'Power exceeds approved limit',
      severity: 'Critical',
      state: 'Open',
      owner: 'Unassigned',
      age: '12m',
      site: 'IDEA Factory A',
      area: 'Utility Area',
      asset: 'Main Panel A',
      pointId: 'point-power-a',
      point: 'MAIN-PANEL-A-POWER',
      ruleId: 'PWR-001',
      ruleVersion: 3,
      triggerValue: '128.7 kW',
      threshold: '> 120 kW',
      duration: '5m 12s',
      quality: 'Good',
      createdAt: '23/07/2026 10:13:00 ICT',
      firstTrigger: '10:13',
      recoveryAt: null,
      summary: 'Active power remained above 120 kW for more than 5 minutes.',
      timeline: [
        { time: '10:13', type: 'System', title: 'Alert created', text: 'Rule PWR-001 v3 confirmed a sustained threshold violation.' },
        { time: '10:13', type: 'Notification', title: 'In-app notification sent', text: 'Operator and Manager recipients notified.' },
        { time: '10:14', type: 'Notification', title: 'Email delivery scheduled', text: 'Critical alert escalation policy applied.' }
      ]
    },
    {
      id: 'ALT-2026-0027',
      title: 'Compressor power near upper operating range',
      severity: 'High',
      state: 'Acknowledged',
      owner: 'Nguyễn An',
      age: '31m',
      site: 'IDEA Factory A',
      area: 'Compressed Air',
      asset: 'Compressor A',
      pointId: 'point-compressor-a',
      point: 'COMPRESSOR-A-POWER',
      ruleId: 'PWR-001',
      ruleVersion: 3,
      triggerValue: '122.4 kW',
      threshold: '> 120 kW',
      duration: '6m 03s',
      quality: 'Good',
      createdAt: '23/07/2026 09:54:00 ICT',
      firstTrigger: '09:54',
      recoveryAt: null,
      summary: 'Compressor A is operating above the approved power threshold.',
      timeline: [
        { time: '09:54', type: 'System', title: 'Alert created', text: 'Threshold violation confirmed.' },
        { time: '09:58', type: 'User', title: 'Acknowledged by Nguyễn An', text: 'Operator accepted responsibility.' }
      ]
    },
    {
      id: 'ALT-2026-0021',
      title: 'Voltage variation',
      severity: 'Medium',
      state: 'In Progress',
      owner: 'Trần B',
      age: '2h',
      site: 'IDEA Factory A',
      area: 'Production Line 1',
      asset: 'Compressor C',
      pointId: 'point-power-a',
      point: 'VOLTAGE-C',
      ruleId: 'VOLT-003',
      ruleVersion: 1,
      triggerValue: '368 V',
      threshold: '< 370 V',
      duration: '9m',
      quality: 'Uncertain',
      createdAt: '23/07/2026 08:24:00 ICT',
      firstTrigger: '08:24',
      recoveryAt: null,
      summary: 'Voltage variation requires investigation.',
      timeline: [
        { time: '08:24', type: 'System', title: 'Alert created', text: 'Low-voltage threshold violation.' },
        { time: '08:32', type: 'User', title: 'Investigation started', text: 'Trần B is reviewing source quality.' }
      ]
    },
    {
      id: 'ALT-2026-0018',
      title: 'Source interrupted',
      severity: 'Low',
      state: 'Recovered',
      owner: 'Lê C',
      age: '5h',
      site: 'IDEA Factory A',
      area: 'Utility Area',
      asset: 'REST-01',
      pointId: 'point-power-a',
      point: 'REST-01',
      ruleId: 'NODATA-004',
      ruleVersion: 2,
      triggerValue: 'No data',
      threshold: '5 minute grace period',
      duration: '7m 44s',
      quality: 'Missing',
      createdAt: '23/07/2026 05:05:00 ICT',
      firstTrigger: '05:05',
      recoveryAt: '05:13',
      summary: 'Data flow recovered, but the alert still requires review and closure.',
      timeline: [
        { time: '05:05', type: 'System', title: 'No Data alert created', text: 'Expected interval exceeded.' },
        { time: '05:13', type: 'System', title: 'Condition recovered', text: 'Data resumed. Alert remains open for review.' }
      ]
    },
    {
      id: 'ALT-2026-0012',
      title: 'Temperature high',
      severity: 'Medium',
      state: 'Open',
      owner: 'Unassigned',
      age: '1d',
      site: 'IDEA Factory A',
      area: 'Production Line 2',
      asset: 'AHU-1',
      pointId: 'point-power-a',
      point: 'AHU-1-TEMP',
      ruleId: 'TEMP-002',
      ruleVersion: 1,
      triggerValue: '32.8 °C',
      threshold: '> 30 °C',
      duration: '18m',
      quality: 'Good',
      createdAt: '22/07/2026 10:21:00 ICT',
      firstTrigger: '10:21',
      recoveryAt: null,
      summary: 'Temperature remained above the approved limit.',
      timeline: [
        { time: '10:21', type: 'System', title: 'Alert created', text: 'Temperature threshold violation.' }
      ]
    }
  ],
  csvImport: {
    filename: 'utility_readings_2026-07-22.csv',
    total: 12000,
    valid: 11820,
    warnings: 120,
    invalid: 40,
    duplicates: 20,
    rows: [
      { row: 1, point: 'MAIN-PANEL-A-POWER', timestamp: '22/07/2026 00:00', value: '118.5', unit: 'kW', status: 'Valid', reason: '—' },
      { row: 2, point: 'MAIN-PANEL-A-POWER', timestamp: '22/07/2026 00:01', value: '119.2', unit: 'kW', status: 'Valid', reason: '—' },
      { row: 3, point: 'MAIN-PANEL-A-POWER', timestamp: '22/07/2026 00:02', value: '—', unit: 'kW', status: 'Invalid', reason: 'VALUE_REQUIRED — Missing value' },
      { row: 4, point: 'MAIN-PANEL-A-POWER', timestamp: '22/07/2026 00:03', value: '121.0', unit: 'kW', status: 'Valid', reason: '—' },
      { row: 5, point: 'COMPRESSOR-A-POWER', timestamp: '22/07/2026 00:04', value: '95.3', unit: 'kW', status: 'Warning', reason: 'LATE_MEASUREMENT — Outside normal arrival window' },
      { row: 6, point: 'MAIN-PANEL-A-POWER', timestamp: '22/07/2026 00:01', value: '119.2', unit: 'kW', status: 'Duplicate', reason: 'DUPLICATE_MEASUREMENT — Same point and timestamp' },
      { row: 7, point: 'UNKNOWN-POINT', timestamp: '22/07/2026 00:05', value: '15.3', unit: 'kW', status: 'Invalid', reason: 'POINT_NOT_FOUND — Point is not configured' },
      { row: 8, point: 'COMPRESSOR-A-POWER', timestamp: '22/07/2026 00:06', value: '96.1', unit: 'kW', status: 'Valid', reason: '—' }
    ]
  }
};
